-- Complete consent management schema
-- Adds all required consent columns and audit table
-- KVKK Compliance Enhancement

-- Add missing consent columns to profiles
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS age_verified BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS marketing_consent BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS terms_accepted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS kvkk_accepted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS marketing_consent_at TIMESTAMPTZ;

-- Create consent audit log table
CREATE TABLE IF NOT EXISTS consent_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  consent_type TEXT NOT NULL CHECK (consent_type IN ('terms', 'kvkk', 'age', 'marketing', 'data_transfer', 'special_category')),
  given BOOLEAN NOT NULL,
  ip_address INET,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_consent_audit_user_id ON consent_audit(user_id);
CREATE INDEX IF NOT EXISTS idx_consent_audit_created_at ON consent_audit(created_at);

-- Enable RLS
ALTER TABLE consent_audit ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can only see their own consent history
CREATE POLICY "Users can view own consent history"
  ON consent_audit
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- RLS Policy: Service role can insert consent records
CREATE POLICY "Service role can insert consent records"
  ON consent_audit
  FOR INSERT
  TO service_role
  WITH CHECK (true);

-- Add comments for documentation
COMMENT ON TABLE consent_audit IS 'KVKK compliance: tracks all consent events with timestamp and IP';
COMMENT ON COLUMN consent_audit.consent_type IS 'Type of consent: terms, kvkk, age, marketing, data_transfer, special_category';
COMMENT ON COLUMN consent_audit.given IS 'True if consent given, false if withdrawn';

